nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: 
      - 'https://ravina-luhu.vercel.app'
      - 'http://localhost:5173'
      - 'http://127.0.0.1:5173'
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
    expose_headers: ['Link', 'Authorization']
    max_age: 3600
  paths:
    '^/api':
      allow_origin: 
        - 'https://ravina-luhu.vercel.app'
        - 'http://localhost:5173'
        - 'http://127.0.0.1:5173'
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
      expose_headers: ['Link', 'Authorization']
      max_age: 3600
